### ISSUE TITLE
Update status in merged PR's

### ISSUE THREAD

**Issue by TiagoDanin** [pr-triage/app#106]
**Summary**
Add status for merged pull requests without approval.

Issue type: Suggestion

**Current Behavior**:
![image](https://user-images.githubusercontent.com/5731176/47168745-0b59bf00-d2d8-11e8-8a73-f6fbf2730cc8.png)

**Expected behavior (Suggestion)**
![image](https://user-images.githubusercontent.com/5731176/47168858-61c6fd80-d2d8-11e8-88c3-369788089bbb.png)

**Comment by sotayamashita** [comment]
@TiagoDanin I understand the your request. I would appreciate if you could create a pull request for this. :smile:

**Comment by sotayamashita** [comment]
Close it. @TiagoDanin did great work.
