### ISSUE TITLE
"PR: unreviewed" forgotten

### ISSUE THREAD

**Issue by Berkmann18** [pr-triage/app#119]
### Summary

The bot forgot (a few times) to remove the `PR: unreviewed` either when it was **mistakenly** added alongside `PR: reviewed-approved` (shouldn't that label be `PR: review-approved`?) like in [here](https://github.com/Berkmann18/ServerBuilder/pull/35#pullrequestreview-179714208) or and simply forgot to remove it when a review was approved or changes were requested.
### Steps to reproduce
Have someone or a bot open a PR, have a bot (say access-lint) approve the review and watch.

### What is the current *bug*'s behaviour?
It seems to be activating two events causing a mix of labelling which could persist even after the PR was closed or merged.

### What is the expected *correct* behaviour?

The bot should add and remove the correct label whether a bot or human approved a PR or requested changes to it.

### Relevant logs and/or screenshots

There are other repos where that bug occurred but it can be reflected by the [example](https://github.com/Berkmann18/ServerBuilder/pull/35#pullrequestreview-179714208) above.

### Possible fixes
Possibly adding more checks to ensure that PRs, where _multiple_ reviews are requested that it takes into account when one is an approval and the other one, is either blank (read unreviewed) or requesting changes.

**Comment by sotayamashita** [comment]
@Berkmann18 Thank you for the detailed explanation. I will look the issue deeply on this weekend.

**Comment by sotayamashita** [comment]
@Berkmann18 I have not looked into it because I was tied up. I would appreciate if you could create a pull request to fix this issue.

**Comment by Berkmann18** [comment]
@sotayamashita Okay, no problem.
I'll have a go (although the private key can't be found when running `npm run start:dev`).

**Comment by sotayamashita** [comment]
@Berkmann18 Let me create a guide for your contribution.

**Comment by Berkmann18** [comment]
@sotayamashita I've looked at the CONTRIBUTING.md file but it seems that the `.env` file doesn't work properly or if I missed a bit on where the private key should be and what name it should have despite the fact that the `cat ...` command work on the CLI.

**Comment by sotayamashita** [comment]
@Berkmann18 

If you run the App, you do not load the private key in `.env`.  I have updated the [CONTRIBUTION.md](https://github.com/pr-triage/app/blob/master/CONTRIBUTING.md). I hope it helps you.
