### ISSUE TITLE
Which should be prioritized WIP or draft?

### ISSUE THREAD

**Issue by sotayamashita** [pr-triage/app#176]
In the current implementation, PRTriage prioritize `WIP` over `draft`. I think It just doesn't feel right to me.  What do you think?

*** Update ***
 I am leaving it open for at least ~14~ 7 days to give time for you to raise any concerns.
(14 days is too long)

**Comment by TiagoDanin** [comment]
We should prioritize the `draft`. `Draft` is the new `WIP`.

**Comment by sotayamashita** [comment]
@TiagoDanin I agree.

**Comment by tannakartikey** [comment]
I shall implement it

**Comment by sotayamashita** [comment]
It would be awesome if you, @tannakartikey have a time.

**Comment by sotayamashita** [comment]
@tannakartikey Are you implementing this feature? If you will not, I will do in this weekend.

**Comment by tannakartikey** [comment]
I haven't started yet. Please, feel free to go ahead.

**Comment by sotayamashita** [comment]
I also have not started yet.

**Comment by sotayamashita** [comment]
@tannakartikey I have created the PR. I would appreciate if you could review my PR.

**Comment by tannakartikey** [comment]
@sotayamashita sure!
