### ISSUE TITLE
Support multiple PR reviews

### ISSUE THREAD

**Issue by byzyk** [pr-triage/app#194]
**Is your feature request related to a problem? Please describe.**

There are a lot of people on our team so we require at least 2 PR approvals on some branches. Unfortunately, the bot doesn't seem to recognize this. It adds `APPROVED` label as soon as at least one approval is received, which is confusing.

**Describe the solution you'd like**

It'd be great if the bot could access repo settings and check how many approvals are required before updating labels.

**Describe alternatives you've considered**

N/A

**Additional context**

I'd be more than happy to help with the PR.

**Comment by gundalow** [comment]
When you have a large backlog, I wonder if a label indicating one more review is needed would help keep the backlog moving.

new_pre --> PR: unreviewed --> PR: reviewed-changes-requests --> **PR: partially-approved** --> PR: reviewed-approved --> PR: merged

(may need a better name)

Then maintainers can search for PRs that need just a little more help getting merged.

**Comment by sotayamashita** [comment]
@gundalow I like your idea. 

PRTriage would triage pull request with the following rule:
- PRTriage adds `PR: unreviewed` when a pull request is created.
- PRTriage adds `PR: reviewed-changes-requests` when one of the reviewers ask to need a change
- PRTriage adds `PR: partially-approved` when one of the reviewers approves the change.
- PRTriage adds `PR: reviewed-approved` when every reviewer approves the change.
- PRTriage adds `PR: merged` when that pull request is merged.

**Comment by sotayamashita** [comment]
Incidentally, I would like to change the name of `PR: reviewed-approved` because I think this name is not **intuitive**. `PR: ready-to-merge` would be more intuitive what do you think?

**Comment by gundalow** [comment]
> Incidentally, I would like to change the name of `PR: reviewed-approved` because I think this name is not **intuitive**. `PR: ready-to-merge` would be more intuitive what do you think?

or maybe just `PR: reviewed`?

**Comment by gundalow** [comment]
How would the bot know how many reviews are needed? Could it read [branch protections](https://help.github.com/en/github/administering-a-repository/about-required-reviews-for-pull-requests) via the API? If that isn't set, default to `1`, which matches the current functionality.

**Comment by sotayamashita** [comment]
@gundalow 

> or maybe just PR: reviewed?

It is very simple but I think we cannot guess the next action of PR and `PR: reviewed` might be recognized as approved or changes-requests.

**Comment by sotayamashita** [comment]
> How would the bot know how many reviews are needed?

We can get the number with https://developer.github.com/v3/pulls/review_requests/#list-review-requests

> Could it read branch protections via the API?

Yes. We can get the number with https://developer.github.com/v3/repos/branches/#get-branch-protection

> If that isn't set, default to 1, which matches the current functionality.

I got it.

**Comment by byzyk** [comment]
Just a small comment from my end if I may. 

I'm not sure whether `PR: ready-to-merge` should be used since PR might receive all required approvals but CI or other GitHub checks might fail, meaning despite all the approvals PR is not really ready to merge.

**Comment by maestromac** [comment]
Perhaps keeping it `reviewed-approved` is the path of least resistance for now and we should leave it for https://github.com/pr-triage/app/issues/88

**Comment by gundalow** [comment]
> Perhaps keeping it `reviewed-approved` is the path of least resistance for now and we should leave it for #88

Sounds good to me.

**Comment by allout58** [comment]
I'm planning to take a crack at a PR for this issue this afternoon. Any other thoughts before I start working on it?

**Comment by allout58** [comment]
It looks like https://developer.github.com/v3/repos/branches/#get-branch-protection doesn't actually return the `required_approving_review_count` property like the documentation claims. This is probably a bug with the API, but it means I can't really verify that my changes on that front do anything.
