### ISSUE TITLE
PR Triage stopped picking up new PRs and reviews

### ISSUE THREAD

**Issue by stevelacey** [pr-triage/app#221]
**Is your feature request related to a problem? Please describe.**

I don't think we changed anything on our organization but PR Triage no longer labels things correctly at all:

- New PRs are not labelled `unreviewed`, that consistently never happens
- PRs are not relabelled when PRs are approved or changes requested, also never happens
  - Note: even if we apply the `unreviewed` label ourselves (no idea if this would matter)
- PRs ARE relabelled correctly when merges happen... this seems to still work fine, any existing labels are removed and the `PR: Merged` label is added

**Describe the solution you'd like**

I would like PR Triage to work correctly as it did a couple of weeks ago 🙃

**Describe alternatives you've considered**

We've attempted reinstalling the app numerous times, my best guess is that something changes about the way hooks work, and now PR Triage is only picking up the merge hook? I am curious if anyone else is experiencing this or it's something unique about our organization.

**Comment by maestromac** [comment]
We're having the same issue too.

**Comment by allout58** [comment]
I've had the issue recently too. Pulled down the the repo and set up a dev app for some debugging. It appears that Probot got updated again, changing the API so the app can't get the list of reviews anymore. I'll try to put together a PR shortly to fix it.

**Comment by allout58** [comment]
If I'm reading the code correctly, Draft PRs should also get the correct label, it's just the labels that depend on looking at the actual reviews (the useful part) that are erroring.

**Comment by twomedia** [comment]
Experiencing this as well

**Comment by sotayamashita** [comment]
@stevelacey @maestromac @allout58 @twomedia 

I am sorry not to fix this issue very quickly but @allout58 created a pull request for it.
I am gonna think of the way to prevent the issue again.

**Comment by allout58** [comment]
I think TypeScript could help, in that it would complain if things like this changed underneath the code. I'm more familiar with using TS completely, but I believe there is a way to get it to just run type checks on JS code

**Comment by sotayamashita** [comment]
@allout58 I am thinking to migrate it with TypeScript. Let's discuss here #228
