### ISSUE TITLE
Doesn't seem to be working right now

### ISSUE THREAD

**Issue by maestromac** [pr-triage/app#229]
We're not getting automatic triages starting about. Potentially related to the latest deploy? I'm happy to provide any more info if needed.

**Comment by sotayamashita** [comment]
I am gonna investigate the issue. Sorry for the inconvenience.
I am gonna fix it on Friday, March 13 in Japan time.

**Comment by sotayamashita** [comment]
@maestromac it works right now and I keep to investigate

**Comment by maestromac** [comment]
I just double checked and it seems to be working now. Sorry for the false alarm!
