### ISSUE TITLE
Bot created PRs are not being triaged

### ISSUE THREAD

**Issue by nesl247** [pr-triage/app#74]
When a bot such as Dependabot opens a PR, it is not being triaged (labeled). These cases are still useful because we still need to review these, and it helps us mark what PRs may or may not be reviewed.

**Comment by sotayamashita** [comment]
@nesl247 I am considering it now. Here is relevant part. https://github.com/pr-triage/app/blob/master/index.js#L23-L26. I agree with your use case so I'll remove the code.

**Comment by sotayamashita** [comment]
@nesl247 I have merged the pr. It should be cool :sunglasses:.

**Comment by nesl247** [comment]
Thanks!
