### ISSUE TITLE
Listen to review dismissals

### ISSUE THREAD

**Issue by nesl247** [pr-triage/app#78]
### Summary

When a review is dismissed, the status should update based on other reviews. If there are no other reviews, it should go back to unreviewed. If there are other reviews, the status should depend on them.

### Steps to reproduce

Review a PR and approve it. Then dismiss the review.

### What is the current *bug* behavior?

The label stays the same.

### What is the expected *correct* behavior?

The label is removed and goes back to unreviewed.

**Comment by sotayamashita** [comment]
@nesl247 Sorry not to replay it. I appreciate your feedback. I'll look into it.

**Comment by sotayamashita** [comment]
@nesl247 I fixed the issue and released. Thank you for your help.

**Comment by nesl247** [comment]
Thanks!
