### ISSUE TITLE
public/assets/flow.png has typo

### ISSUE THREAD

**Issue by janpio** [pr-triage/app#97]
"PR: unreviewd" should be "PR: unreview_e_d".
image is also used on https://probot.github.io/apps/pr-triage/

**Comment by sotayamashita** [comment]
@janpio 

I appreciate that you create the issue. I have already known it and I will fix it in this weekend. 

By the way, have you ever tried the pr-triage? I would appreciate if you could give me a feedback.

**Comment by sotayamashita** [comment]
@janpio 

> Not yet, but I looked through lots of Probot apps to find interesting ones and this is definitely one I will try later! Nice work.

Thanks :smile:

> PS: I just noticed, if you are fixing the graphic, you could also replace "I WILL ADD A LABEL DEPENDS ON PR STATUS!" with "I WILL ADD A LABEL DEPENDING ON THE PR STATUS!"

Thanks

**Comment by sotayamashita** [comment]
Fix image. Thanks
